### ISSUE TITLE
Free Extension Settings

### ISSUE THREAD

**Issue by yelled1** [matt035343/interactive-scala#11]
It would be better to just have free extension setting, rather than choice between the two ['scala', 'sbt'].
I am currently using it for glue-spark-shell (AWS).
I just fake it using scala as symlink to glue-spark-shell, but would be better to get just a string option where I can put in anything, which should be local directory settable.
As I am doing with python REPL below:
```
$ cat ../new_glue/.vscode/settings.json
{
    "python.pythonPath": "/usr/bin/gluepython3"
}
```
Not in hurry as I can get around it, but would be nice to have in sometime in the future.
Right now, I would just love to see the cursor not go down to REPL after execution.
Thanks!

**Comment by matt035343** [comment]
I have noted your request, I will take a look soon

**Comment by matt035343** [comment]
This change has been developed and will be released soon.
